#-----------------------------------------------------------------------------------------------------------------------
# All example patches and configurations are listed here.
#-----------------------------------------------------------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spinnaker

resources:
  - infrastructure/mysql.yml           # (Optional, not for production use). MySQL server needed if using SQL backend in Spinnaker

components:
  - core/base
  - core/persistence/in-cluster
  - targets/kubernetes/default

bases:
  - plugins/armory-agent                    # (Optional). Alternate implementation for kubernetes deployments. Requires either plugins/armory-agent/patch-clouddriver-docker.yaml or plugins/armory-agent/patch-clouddriver-repo.yaml, and persistence/patch-sql-clouddriver.yml

patchesStrategicMerge:
  - persistence/patch-sql-clouddriver.yml          ## setup clouddriver to use SQL for storage
  - core/patches/version.yml                            ## Set the deployed Spinnaker version
  - plugins/armory-agent/patch-clouddriver-repo.yaml # or plugins/armory-agent/patch-clouddriver-docker.yaml # Requires persistence/patch-sql-clouddriver.yml and the base dir plugins/armory-agent
  - expose/patch-lb.yml